### ISSUE TITLE
Style issue: Forward/back buttons partly covered by Copyright footer

### ISSUE THREAD

**Issue by kfrn** [LegalCheck/main#33]
Hi all, I noticed that the next/back buttons are now partly disappearing behind the copyright footer.

Here's a screenshot:
![legalcheckup-nav-buttons](https://cloud.githubusercontent.com/assets/16832997/24078774/d39f6eca-0cdb-11e7-9b4b-b2962afa8df6.png)

I'm seeing this when running locally (not looking at the deployed version). On master, completely up to date.

It didn't look like this before, so maybe it's something to do with implementing the copyright modal? (#27)

@katenorquay or @FlightOfGrey, is one of you able to look at it in the next days? Thank you :)

**Comment by gabrielamelian** [comment]
Fixed with pull request #38
